version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build: ./backend
    # ... (rest of backend config)
    networks:
      - app-network

  frontend:
    build: ./frontend
    # ... (rest of frontend config)
    networks:
      - app-network

volumes:
  mysql_data:

# THIS NETWORK DEFINITION MUST EXIST
networks:
  app-network:
    driver: bridge