version: '3.8'

services:
  backend:
    build: ./backend
    image: $DOCKER_HUB_USERNAME/fullstack-app-backend:latest
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: usersdb
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: usersdb
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    image: $DOCKER_HUB_USERNAME/fullstack-app-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: